### ISSUE TITLE
Document how to run with a UI

### ISSUE THREAD

**Issue by ghost** [kiva/protocol-integration-tests#19]
Once https://github.com/kiva/ssi-wizard-sdk/issues/67 and https://github.com/kiva/protocol-gateway/issues/41 are complete, document here how to run the entire Protocol stack on localhost.

**Comment by matt-raffel-kiva** [comment]
I am adding the following work breakout, per the stand alone install feature brief.  Please review the feature brief.  I believe the following work items cover all of the requirements.

- [x] [get the front end running locally.  There is a configuration change required.](https://github.com/kiva/protocol-integration-tests/issues/28)
- [x] [fingerprint reader runs in docker](https://github.com/kiva/protocol-integration-tests/issues/33)
- [x] [get the front end running on both Mac](https://github.com/kiva/protocol-integration-tests/issues/30)
- [x] [and Windows](https://github.com/kiva/protocol-integration-tests/issues/29)
- [x] get the back end running on windows (combine this step with the documentation step below)
- [x] get the back end running in macos.  (calling this done but leaving it here to help shape our thinking)
- [x] [writing step by step documentation for running entire stack on windows](https://github.com/kiva/protocol-integration-tests/issues/31)
- [x] [writing step by step documentation for running entire stack on macos](https://github.com/kiva/protocol-integration-tests/issues/32)
- [x] fixing the [authentication model](https://github.com/kiva/protocol-gateway/issues/41)
